---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on tag push, validates and promotes draft release
name: 'Release on Tag Push 🚀'

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '**'

permissions: {}

jobs:
  validate_tag:
    name: 'Validate Tag'
    # Skip tag deletion events
    if: "!github.event.deleted"
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 5
    outputs:
      tag: "${{ steps.tag_validate.outputs.tag_name }}"
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # v2.19.4
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: 'Verify pushed tag'
        id: tag_validate
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-validate-action@bc8043ec074495cc8cdf351623ebab3675d563cf  # v1.0.4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          require_type: 'semver'
          reject_development: 'true'
          require_github: 'true'
          # yamllint disable-line rule:line-length
          require_signed: 'ssh,gpg-unverifiable'  # Cannot verify GPG without key

  promote_release:
    name: 'Promote Draft Release'
    needs: validate_tag
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # v2.19.4
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: 'Promote draft release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/draft-release-promote-action@072990900b99030363d81d4131c2bf2855f07df0  # v0.1.4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.validate_tag.outputs.tag }}"
          latest: true
